version: '3'

services:
  feature-toggles-db:
    image: mysql:8.0.32
    container_name: feature-toggles-db
    environment:
      MYSQL_DATABASE: featuretoggles
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - feature-toggle-network

  feature-toggles-backend:
    image: joaoguipan/feature-toggles-backend:latest
    container_name: feature-toggles
    build:
      context: ./feature-toggles-api
    environment:
#      - SPRING_PROFILES_ACTIVE=prod
      - DB_HOST=feature-toggles-db
    ports:
      - "8080:8080"
    depends_on:
      - feature-toggles-db
    networks:
      - feature-toggle-network

  feature-toggles-gateway:
    image: joaoguipan/feature-toggles-gateway:latest
    container_name: feature-toggles-gateway
    build:
      context: ./feature-toggles-gateway
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "9999:9999"
    depends_on:
      - feature-toggles-backend
    networks:
      - feature-toggle-network

  feature-toggles-frontend:
    image: joaoguipan/feature-toggles-frontend:latest
    container_name: feature-toggles-ui
    build:
      context: ./feature-toggles-front
    environment:
      SERVER_NAME: localhost
      API_URL: http://host.docker.internal:9999/
    ports:
      - "80:80"
    depends_on:
      - feature-toggles-db
      - feature-toggles-backend
      - feature-toggles-gateway
    networks:
      - feature-toggle-network

networks:
  feature-toggle-network:
    driver: bridge