version: '3'

services:
  feature-toggles-db:
    image: mysql:8.0.32
    container_name: feature-toggles-db
    environment:
      MYSQL_DATABASE: featuretoggles
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - feature-toggle-network

  feature-toggles-backend:
    image: feature-toggles-backend:latest
    container_name: feature-toggles
    build:
      context: ./feature-toggles-api
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      # - DB_HOST=feature-toggles-db
      # - DB_PORT=3306
      # - DB_NAME=featuretoggles
      # - DB_USER=root
      # - DB_PWD=password
      # - DB_URI=jdbc:mysql://feature-toggles-db:3306/featuretoggles?useSSL=false&serverTimezone=Europe/Amsterdam
    ports:
      - 8080:8080
    depends_on:
      - feature-toggles-db
    networks:
      - feature-toggle-network
  
  feature-toggles-frontend:
    image: feature-toggles-frontend:latest
    container_name: feature-toggles-ui
    build:
      context: ./feature-toggles-front
    environment:
      SERVER_NAME: localhost
      API_URL: http://host.docker.internal:8080/
    ports:
      - 80:80
    depends_on:
      - feature-toggles-db
      - feature-toggles-backend
    networks:
      - feature-toggle-network

networks:
  feature-toggle-network:
    driver: bridge