
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:172.29.0.2}:${DB_PORT:3306}/${DB_NAME:featuretoggles}?user=${DB_USER:root}&useSSL=false&serverTimezone=Europe/Amsterdam&allowPublicKeyRetrieval=true
    # url: ${DB_URI:jdbc:mysql://localhost:3306/featuretoggles?user=root&useSSL=false&serverTimezone=Europe/Amsterdam}
    password: ${DB_PWD:password}
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: Europe/Amsterdam
          format_sql: true